### ISSUE TITLE
Eliminate shared.py

### ISSUE THREAD

**Issue by robertdstein** [icecube/flarestack#12]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I realise shared.py is a redundant pseudo-init file

**Describe the solution you'd like**
Everything from shared should be moved to __init__.py.

**Describe alternatives you've considered**
Leaving as is. Less time, but less readable for people who aren't me.

**Comment by mlincett** [comment]
Is this still relevant and/or desired?

Personally I am not a fan of heavy `__init__.py` files: hard to establish what should belong to them and hard to figure out that something is defined there.

I personally use them for packaging purposes / import and "exports".
