### ISSUE TITLE
AttributeError: type object 'LargeCatalogueMinimisationHandler' has no attribute 'compatible_injectors'

### ISSUE THREAD

**Issue by smechbal** [icecube/flarestack#127]
When calling `LargeCatalogueMinimisationHandler` in `minimisation.py`, it looks for what seems like a deprecated class attribute `compatible_injectors`

**Comment by JannisNe** [comment]
Can you post the error message?

**Comment by smechbal** [comment]
claro

<img width="1168" alt="Screenshot 2022-02-18 at 11 21 24" src="https://user-images.githubusercontent.com/23045171/154664117-4cde376b-a1f5-461f-89ee-471bc956d963.png">
