### ISSUE TITLE
Exception handling in `ic_season.get_published_sens_ref_dir()`

### ISSUE THREAD

**Issue by mlincett** [icecube/flarestack#166]
It is not clear to me how the exception handling is supposed to work in the following:
https://github.com/icecube/flarestack/blob/ca3cf40a47f80ae0717c828bd5564ba496c18965/flarestack/data/icecube/ic_season.py#L58-L68

From the rest of the module, I see no way a `NameError` can be caught there, but `ref_dir_7yr`, `ref_10yr` will rather have `None` values.

Once we agree on the desired behaviour I am happy to follow-up on the issue.

**Comment by mlincett** [comment]
To be fair, this is not the only inconsistency. `ref_dir_7yr` is initialised in:
https://github.com/icecube/flarestack/blob/517d44fc5d664322174021d3c7e87882b0eaef41/flarestack/data/icecube/ic_season.py#L16-L23
and immediately overridden by:
https://github.com/icecube/flarestack/blob/517d44fc5d664322174021d3c7e87882b0eaef41/flarestack/data/icecube/ic_season.py#L25-L33

These two environment variables are not referenced anywhere else in the code so I guess L25-33 can be dropped.

**Comment by JannisNe** [comment]
You are right. Then also again override by

https://github.com/icecube/flarestack/blob/517d44fc5d664322174021d3c7e87882b0eaef41/flarestack/data/icecube/ic_season.py#L35-L55

Feel free to think of anything that's more consistent. The important thing is to keep it backwards compatible.

**Comment by mlincett** [comment]
I think I will rewrite this part, indeed.

Any objections if I use [`pathlib`](https://docs.python.org/3/library/pathlib.html#module-pathlib)? It allows for more robust and elegant handling of paths in comparison to `os.path`.

**Comment by robertdstein** [comment]
Though I may well have been the one to write this in the first place, I think the code in ic_season lines 25 to 33 should probably just read:
```
ref_dir_7yr = os.environ.get("7YR_SENS_REF")
ref_10yr = os.environ.get("10YR_SENS_REF")
```
since that will set the refs to `None` if the environment variables are not set, rather than raising a `KeyError`. Basically I think we should never do `os.environ["x/y/x"]` in the code.

And yeah I agree that `Pathlib` is a good option, though honestly even `os.path` would be more robust than `+` for strings.

**Comment by mlincett** [comment]
> Though I may well have been the one to write this in the first place, I think the code in ic_season lines 25 to 33 should probably just read:
> 
> ```
> ref_dir_7yr = os.environ.get("7YR_SENS_REF")
> ref_10yr = os.environ.get("10YR_SENS_REF")
> ```

Sure, this make sense. I found no other reference in the code or in the documentation to the possibility of passing these as individual environment variables, but we can keep supporting it as it does not cost much.

**Comment by JannisNe** [comment]
Thanks @mlincett! Can I close this now?
