### ISSUE TITLE
`VisibleDeprecationWarning` in llh.py

### ISSUE THREAD

**Issue by mlincett** [icecube/flarestack#174]
Trying to test a stacking analysis with a box-like time PDF, I get the following warning:
```
kwargs["SoB_spacetime_cache"] = np.array(SoB_spacetime)
/lustre/fs20/group/icecube/mlincett/software/flarestack/flarestack/core/llh.py:912: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
```
Not sure whether this is due to something wrong in my inputs or it is inherent to the way the code currently works, any clue?

**Comment by robertdstein** [comment]
I suspect this is a numpy version change from when I coded it up N years ago. I think just follow the suggestion and do `np.array(SoB_spacetime, dtype=object)`?

**Comment by mlincett** [comment]
It seems this deprecation is in full force in python 3.10.2 so we should likely fix this ASAP.

**Comment by mlincett** [comment]
Fixing this in #266 . Just wanted add here that when this segment of the code throws an exception the program **does not exit**, hence the CI jobs were dangling for hours before getting killed.

**Comment by mlincett** [comment]
After checking a bit better the code structure, it seems there's no real benefit from wrapping `SoB_spacetime_cache` in a numpy array.

Note that this code is only used the "standard" LLH.
