### ISSUE TITLE
time_pdf.DecayPDF fails to properly check for key "decay_length" resulting in misleading KeyErrors

### ISSUE THREAD

**Issue by sgriswol** [icecube/flarestack#183]
**Description**
During initialization of `time_pdf.DecayPDF`, two checks are performed for the "decay_time" key in the user-provided dictionary. The second check (at line 692) produces a warning "No *decay length* given" suggesting that this check should be performed on key "decay_length" rather than "decay_time". 

Additionally, during this init (at line 690), an attempt is made to populate `DecayPDF.decay_length` with a value from the user-provided dictionary. However, this will produce a KeyError if the user-provided dictionary does not contain the "decay_length" key.

This error can be caught by try-catches in other locations, IE llh.py:110. The steps below produces the following error (See attached file as well), which suggests that the `llh_sig_time_pdf" key is missing, even though it is provided. This is caused by a key error at  time_pdf.py:690 as described above.

```No Background Time PDF specified. Please add an 'llh_bkg_time_pdf' entry to the llh_dict, and try again. If you do not want time dependence in your likelihood, please specify a 'steady' Time PDF.```

**To Reproduce**
1. Using `examples/flarestack_llh_workshop.ipynb`
2. in cell 10, replace the definition of `llh_time` with the following
```python
import numpy as np
llh_time = {
    "time_pdf_name": "decay",
    "decay_time": np.inf   
}
```
3. Run remaining cells, cell 16 will produce the relevant error

**Additional context**
Permalink to relevant code: https://github.com/icecube/flarestack/blob/03c9aed8459e445c752e827c3157ed2d5e794302/flarestack/core/time_pdf.py#L679-L693

[flarestack_decay_pdf_keyerror_trace.txt](https://github.com/icecube/flarestack/files/9284631/flarestack_decay_pdf_keyerror_trace.txt)

**Comment by JannisNe** [comment]
You are right, the check should be for the key `decay_length` not `decay_time`.
I will change that shortly.
I see in your example that you want to set the decay time to infinity. Note that that will give you effectively a box PDF with because
$\frac{1}{1 +(t-t_0) / t_{decay}} \overset{t_{decay} \rightarrow \inf}{=}  1$.
Because the PDF is set to 0 after `decay_length`, this gives you a box window with the length of `decay_length`
