### ISSUE TITLE
Flarestack incompatible with latest version of black

### ISSUE THREAD

**Issue by robertdstein** [icecube/flarestack#251]
**Describe the bug**
The newest version of black (v23) has introduced some new rule for removing blank lines. The upshot is that the pylint test, and therefore CI, will now fail unless somebody runs a new version of black on the code.

**To Reproduce**
See e.g https://github.com/icecube/flarestack/actions/runs/4188047327/jobs/7258687765

**Comment by mlincett** [comment]
It could be convenient if the version of `black` run by the workflow could match the one specified by the flarestack dependencies.

I have nothing against running `black` v23 on all the code, but I would exclude the `analyses` subfolder.

**Comment by mlincett** [comment]
It appears from #259 that the test does not fail when it should.

**Comment by mlincett** [comment]
> I think we should require Lint for merging too

It seems simpler than checking for non-required test to succeed before automerging, at least from my brief investigation.

Although I do not have access to the repo settings, maybe you can enable me?

**Comment by mlincett** [comment]
From the release notes of Black 23.3.0:

> This release fixes a longstanding confusing behavior in Black's GitHub action, where the version of the action did not determine the version of Black being run (issue [#3382](https://redirect.github.com/psf/black/issues/3382)). In addition, there is a small bug fix around imports and a number of improvements to the preview style.

So maybe we can switch back to the action.
