### ISSUE TITLE
Proposal to deprecate python 3.8

### ISSUE THREAD

**Issue by mlincett** [icecube/flarestack#301]
Python 3.8 does not support the use of native `tuple` and `list` for type annotations.

Maintaining support python 3.8 means carrying around `from typing import List, Tuple` statements.

Something against discontinuing support for 3.8, @JannisNe , @robertdstein ?

**Comment by JannisNe** [comment]
Nothing against dropping 3.8!

**Comment by mlincett** [comment]
I am trying to make this effective in #302 although it seems I cannot get rid of the CI test for 3.8, even after modifying the workflows file. Maybe I'll have to look deeper.

**Comment by robertdstein** [comment]
This will be fixed by #302
