### ISSUE TITLE
`coveralls` submission error

### ISSUE THREAD

**Issue by JannisNe** [icecube/flarestack#348]
When CI jobs are running they sometimes fail with 
```
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
```
Look at [this CI](https://github.com/icecube/flarestack/actions/runs/8188597539/job/22392131186) job for example.

Not related directly to flarestack but should be fixed.

**To Reproduce**
Not sure as it seems random which of the python versions fail.

**Expected behavior**
All works fine.

**Additional context**
Asked for support directly at coveralls.

**Comment by JannisNe** [comment]
The official coveralls support has answered with a lot of detail. I think we should switch to the official integration action: https://github.com/marketplace/actions/coveralls-github-action

**Comment by robertdstein** [comment]
Sounds like a good idea!
