### ISSUE TITLE
Smarter python path setup for cluster

### ISSUE THREAD

**Issue by robertdstein** [icecube/flarestack#35]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to limit flarestack dependencies to those covered by `cvmfs/icecube...`. In case we ever  wanted new dependencies, or more up to date software versions, things would break. In any case, we shouldn't be forcing a particular method of installing flarestack. 

**Describe the solution you'd like**
Whichever python path used to execute a given flarestack submission script should then be directly written into the generated bash script, and that same python path can then be used by the cluster. That way, we are neutral to which method of flarestack installation is applied, whether it is conda, virtual environment or just "cvmfs&export pythonpath". The PYTHONPATH exporting can continue as normal, as it doesn't harm things. The user is responsible for sorting out their own dependencies, and then the cluster submission can be consistently personalised to each user.

**Describe alternatives you've considered**
Leaving things as is. There will be an overhead because the submitter module will need to be regularly updated to use the most recent cvmfs python iteration. Also restricts from ever exploring new dependencies.

**Comment by mlincett** [comment]
This should have been fixed already in #213
