### ISSUE TITLE
Deprecation of `interp2d`

### ISSUE THREAD

**Issue by JannisNe** [icecube/flarestack#383]
Lately seeing this deprecation warning:

> DeprecationWarning: `interp2d` is deprecated in SciPy 1.10 and will be removed in SciPy 1.14.0.
> 
> For legacy code, nearly bug-for-bug compatible replacements are
> `RectBivariateSpline` on regular grids, and `bisplrep`/`bisplev` for
> scattered 2D data.
> 
> In new code, for regular grids use `RegularGridInterpolator` instead.
> For scattered data, prefer `LinearNDInterpolator` or
> `CloughTocher2DInterpolator`.
> 
> For more details see
> `https://scipy.github.io/devdocs/notebooks/interp_transition_guide.html`

This affects `StandardLLH.create_acceptance_function()`.  SHould be replaced as suggested in the warning.

**Comment by mlincett** [comment]
Ehe, this is there since #270

I assume replacing with `RectBivariateSpline` should be painless.

**Comment by JannisNe** [comment]
Ok, then closing because duplicate of #270
